### ISSUE TITLE
Application wont start on running npm start

### ISSUE THREAD

**Issue by Shobhit28** [IBM/watson-assistant-with-search-skill#6]
Received below error when running npm start from terminal, post the configuration steps

> composite-disco-sdu-assistant-chatbot.gi@1.0.0 start /ibm/watson-assistant-with-search-skill
> node app.js

Assistant auth: {
  "disableSslVerification": false,
  "headers": {},
  "tokenManager": {
    "tokenInfo": {},
    "tokenName": "access_token",
    "disableSslVerification": false,
    "headers": {},
    "requestWrapperInstance": {},
    "requiredOptions": [
      "apikey"
    ],
    "apikey": "************",
    "url": "https://iam.cloud.ibm.com/identity/token"
  },
  "requiredOptions": [
    "apikey"
  ],
  "apikey": "*******"
}
Error creating session:
Not Found: Resource not found
    at RequestWrapper.formatError (ibm/watson-assistant-with-search-skill/node_modules/ibm-cloud-sdk-core/lib/request-wrapper.js:208:21)
    at ibm/watson-assistant-with-search-skill/node_modules/ibm-cloud-sdk-core/lib/request-wrapper.js:196:25
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  statusText: 'Not Found',
  name: 'Not Found',
  status: 404,
  code: 404,
  message: 'Resource not found',
  body: '{"error":"Resource not found","code":404}',
  headers: {
    'content-type': 'application/json; charset=utf-8',
    'content-length': '41',
    'access-control-allow-origin': '*',
    'access-control-allow-methods': 'GET, POST, PUT, DELETE, PATCH, HEAD, OPTIONS',
    'access-control-allow-headers': 'Content-Type, Content-Length, Authorization, X-Watson-Authorization-Token, X-WDC-PL-OPT-OUT, X-Watson-UserInfo, X-Watson-Learning-Opt-Out, X-Watson-Metadata',
    'access-control-max-age': '3600',
    'content-security-policy': "default-src 'none'",
    'x-dns-prefetch-control': 'off',
    'x-frame-options': 'SAMEORIGIN',
    'strict-transport-security': 'max-age=31536000; includeSubDomains;',
    'x-download-options': 'noopen',
    'x-content-type-options': 'nosniff',
    'x-xss-protection': '1; mode=block',
    'x-response-time': '0.436ms',
    'x-global-transaction-id': '***',
    'x-dp-watson-tran-id': '****',
    'x-edgeconnect-midmile-rtt': '233',
    'x-edgeconnect-origin-mex-latency': '143',
    date: 'Thu, 16 Apr 2020 18:38:15 GMT',
    connection: 'close'
  }
}

**Comment by Shobhit28** [comment]
The assistant url mentioned in the UI should be copied just till the start of api version. So the assistant url would look something like https://*******.assistant.watson.cloud.ibm.com/instances/**********-*****-*****-*****-***********
